version: 2
jobs:
    build:
        machine: true
        steps:
            - add_ssh_keys:
                fingerprints:
                    - "b1:f6:75:0e:a2:3c:d0:c3:b1:63:74:18:57:25:93:b4"
            - checkout
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
            - run: docker build -t dockerssbjh/catalog:$CIRCLE_SHA1 .
            - run: docker push dockerssbjh/catalog:$CIRCLE_SHA1
            - run: ssh root@134.209.221.129 "/bin/bash /root/docker/deploy.sh $CIRCLE_SHA1"